### ISSUE TITLE
which mkmf.log to examine?

### ISSUE THREAD

**Issue by ljgww** [rubysl/rubysl-curses#2]
ubunty 14.04

ruby-2.2.0$ sudo gem install rubysl-curses
Building native extensions.  This could take a while...
ERROR:  Error installing rubysl-curses:
	ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -r ./siteconf20150118-16249-b4pxk5.rb extconf.rb
checking for tgetent() in -ltinfo... no
checking for tgetent() in -ltermcap... no
checking for ncurses.h... no
checking for ncurses/curses.h... no
checking for curses_colr/curses.h... no
checking for curses.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-curses-dir
	--without-curses-dir
	--with-curses-include
	--without-curses-include=${curses-dir}/include
	--with-curses-lib
	--without-curses-lib=${curses-dir}/lib
	--with-ncurses-dir
	--without-ncurses-dir
	--with-ncurses-include
	--without-ncurses-include=${ncurses-dir}/include
	--with-ncurses-lib
	--without-ncurses-lib=${ncurses-dir}/lib
	--with-termcap-dir
	--without-termcap-dir
	--with-termcap-include
	--without-termcap-include=${termcap-dir}/include
	--with-termcap-lib
	--without-termcap-lib=${termcap-dir}/lib
	--with-tinfolib
	--without-tinfolib
	--with-termcaplib
	--without-termcaplib

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/rubysl-curses-2.0.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/rubysl-curses-2.0.1/gem_make.out

**Comment by YorickPeterse** [comment]
This Gem is meant to be used on Rubinius, not MRI. The full build output should be in `/usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/rubysl-curses-2.0.1/gem_make.out` as stated by the error itself.

**Comment by ljgww** [comment]
thx for clarifications
